@echo off
REM Google Ads MCP Wrapper — Reads credentials from .env.agents and launches MCP server
REM Server: vendor/mcp-google-ads (cohnen/mcp-google-ads, cloned locally)
REM
REM SETUP (one-time):
REM   1. Fill in GOOGLE_ADS_* values in .env.agents
REM   2. Run:  python scripts/generate_google_ads_token.py
REM      This writes vendor/mcp-google-ads/google_ads_token.json
REM   3. Install server deps:  pip install -r vendor/mcp-google-ads/requirements.txt
REM   Then restart Claude Code — this wrapper will launch the server automatically.

REM Resolve project root (one level up from this script)
set "SCRIPT_DIR=%~dp0"
set "PROJECT_ROOT=%SCRIPT_DIR%.."

REM Parse .env.agents for Google Ads credentials
for /f "usebackq tokens=1,* delims==" %%A in ("%PROJECT_ROOT%\.env.agents") do (
    if "%%A"=="GOOGLE_ADS_DEVELOPER_TOKEN"  set GOOGLE_ADS_DEVELOPER_TOKEN=%%B
    if "%%A"=="GOOGLE_ADS_CLIENT_ID"        set GOOGLE_ADS_CLIENT_ID=%%B
    if "%%A"=="GOOGLE_ADS_CLIENT_SECRET"    set GOOGLE_ADS_CLIENT_SECRET=%%B
    if "%%A"=="GOOGLE_ADS_REFRESH_TOKEN"    set GOOGLE_ADS_REFRESH_TOKEN=%%B
    if "%%A"=="GOOGLE_ADS_CUSTOMER_ID"      set GOOGLE_ADS_LOGIN_CUSTOMER_ID=%%B
)

REM Token JSON path (generated by scripts/generate_google_ads_token.py)
set "GOOGLE_ADS_CREDENTIALS_PATH=%PROJECT_ROOT%\vendor\mcp-google-ads\google_ads_token.json"
set GOOGLE_ADS_AUTH_TYPE=oauth

REM Launch the Google Ads MCP server from vendor clone
python "%PROJECT_ROOT%\vendor\mcp-google-ads\google_ads_server.py"
